### ISSUE TITLE
Unclear DeprecationWarning

### ISSUE THREAD

**Issue by s-kruschel** [masenf/reflex-audio-capture#1]
Hey @masenf,

I just tried to run your reflex-audio-capture demo example. 

However, the app re-renders / re-complies every ~10 seconds and reports the following DeprecationWarning:

> DeprecationWarning: Creating a Var ((refs['mediadevices_ref_myaudio'])) from a string without specifying _var_is_string has been deprecated in version 0.5.4 Specify _var_is_string=False to create a Var that is not a string literal. In the future, creating a Var from a string will be treated as a string literal by default. It will be completely removed in 0.6.0

I already tried to identify the underlying issue. However, as it is unclear where the warning stems from, I don't know where to further look into. 

Do you have any idea? 

Thanks a lot!

**Comment by masenf** [comment]
I believe the issue is fixed by #2, but i'm not sure about the recompiling every 10 seconds thing... are you saving the audio into the app directory? that might trigger a hot reload, which is probably not what you want.

i published the latest change in 0.0.3, let me know if you're still seeing this issue
